/**
* Tracker
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* Contact: aaron.targa@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Location

import com.squareup.moshi.Json
/**
 * 
 * @param location 
 */

data class InlineObject2 (
    @Json(name = "location")
    val location: Location? = null
) 



