/**
* Tracker
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* Contact: aaron.targa@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.LocationLoc

import com.squareup.moshi.Json
/**
 * 
 * @param name 
 * @param loc 
 * @param timestamp 
 * @param speed 
 * @param altitude 
 * @param pulse 
 */

data class Location (
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "loc")
    val loc: LocationLoc? = null,
    @Json(name = "timestamp")
    val timestamp: kotlin.String? = null,
    @Json(name = "speed")
    val speed: java.math.BigDecimal? = null,
    @Json(name = "altitude")
    val altitude: java.math.BigDecimal? = null,
    @Json(name = "pulse")
    val pulse: java.math.BigDecimal? = null
) 



