/**
* Tracker
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* Contact: aaron.targa@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * stores longitude and latitude of user
 * @param longitude 
 * @param latitude 
 */

data class LocationLoc (
    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null,
    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null
) 



