/**
* Tracker
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* Contact: aaron.targa@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param username 
 * @param lastUpdated Seconds since 01-01-1970 00:00:00 UTC
 */

data class User (
    @Json(name = "id")
    val id: kotlin.Int? = null,
    @Json(name = "username")
    val username: kotlin.String? = null,
    /* Seconds since 01-01-1970 00:00:00 UTC */
    @Json(name = "last_updated")
    val lastUpdated: kotlin.Int? = null
) 



